### ISSUE TITLE
Unhandled Exception: Exception: No device found for media generation

### ISSUE THREAD

**Issue by hainm729** [flutterjanus/flutter_janus_client#105]
I run macOS , when i join meeting. it error.
```

flutter: [FINE] JanusClient: disposing localStream and remoteStream if it already exists
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Exception: No device found for media generation
#0      JanusPlugin.initializeMediaDevices (package:janus_client/janus_plugin.dart:551:7)
<asynchronous suspension>
#1      _TypedVideoRoomV2UnifiedState.joinRoom (package:janus_application/typed_examples/video_room.dart:107:5)
<asynchronous suspension>
#2      _TypedVideoRoomV2UnifiedState.build.<anonymous closure> (package:janus_application/typed_examples/video_room.dart:224:19)
<asynchronous suspension>
```

**Comment by shivanshtalwar0** [comment]
This happened to you probably because you haven't specified permissions in info.plist file for mac os build
https://developer.apple.com/documentation/avfoundation/capture_setup/requesting_authorization_for_media_capture_on_macos

**Comment by dev12-dgh** [comment]
@shivanshtalwar0 it still not working .
<img width="821" alt="Ảnh chụp Màn hình 2022-12-16 lúc 10 16 54" src="https://user-images.githubusercontent.com/92362105/208014199-5db31f26-405b-4a9e-8528-1ed41cb0a0a6.png">

**Comment by shivanshtalwar** [comment]
@hainm729 
in file `Runner/DebugProfile.entitlements` under <dict> add
```xml
        <key>com.apple.security.app-sandbox</key>
	<true/>
	<key>com.apple.security.cs.allow-jit</key>
	<true/>
	<key>com.apple.security.device.camera</key>
	<true/>
	<key>com.apple.security.device.microphone</key>
	<true/>
	<key>com.apple.security.network.client</key>
	<true/>
	<key>com.apple.security.network.server</key>
	<true/>
```	
make sure you are on latest version of flutter_webrtc and otherwise latest version of flutter_janus_client
i tested google meet clone(latest example with video audio and screensharing all in one) and it works fine
