### ISSUE TITLE
Extra PayLoad

### ISSUE THREAD

**Issue by Yogesh-Dubey-Ayesavi** [flutterjanus/flutter_janus_client#113]
While initiating a video call i want to send extra payload apart from username how can i do that  ?

**Comment by shivanshtalwar** [comment]
What do you mean extra payload?

**Comment by Yogesh-Dubey-Ayesavi** [comment]
By extra payload I mean to say right now in the demo whenever I call somebody my username appears just what if I want to display his user avatar , show user description ?

**Comment by shivanshtalwar** [comment]
Well that's upto application to manage since janus is general purpose webrtc server so one solution that i can think of is using JSON string as username and then parse it on the application level to show what you require or otherwise you can use your own unique publisher id for every user co related to user in database

**Comment by shivanshtalwar** [comment]
Please ask such questions in discussions closing now

**Comment by Yogesh-Dubey-Ayesavi** [comment]
I thought of this approach but in my case it will cost a lot of db reads. We can send user name  as json string than parse it. Is it would a right approach I don't think so

**Comment by shivanshtalwar** [comment]
Please look at janus documentation its not one stop shop for everything it does what it is intended to do application level stuff you have to think and develop and if you concerned about too many db request then maybe you can consider using redis to cache data and introduce more complexity to the system but in my opinion it would be an overkill even if there are 500 reads per video room which in case of single janus instance is impossible
But yes in case you are orchestrating multiple janus instances on kubernetes 500 reads is still less per room
