### ISSUE TITLE
could not allocate rtp/rtcp ports

### ISSUE THREAD

**Issue by makspuzzz** [flutterjanus/flutter_janus_client#119]
Hello friends! I am glad that the data I provided helps you develop the plugin!
During my use of the plugin, the following error occurred with incoming videos "could not allocate rtp/rtcp ports". Is there any solution?

**Comment by shivanshtalwar** [comment]
Without any context, I am afraid i can't help you, consider updating description briefly of your problem and use case

**Comment by makspuzzz** [comment]
This happens when I receive an incoming video call to my SIP account.

**Comment by shivanshtalwar0** [comment]
This error seems like janus error you probably want to ask this question at janus repository
Closing.
