### ISSUE TITLE
SIP impl for FreeSwitch

### ISSUE THREAD

**Issue by mohbadar** [flutterjanus/flutter_janus_client#126]
Can anyone help me with using this repo for connecting to FreeSwitch through SIP and performing these tasks:
 - Manage incoming and outgoing calls
 - Transfer calls (with or without consultation) 
 - Send and receive messages
  
I would be grateful for your helpful information.

**Comment by shivanshtalwar** [comment]
This should be asked as a community question since it is not a bug therefore closing
