### ISSUE TITLE
how to add Simulcast support in video room plugin?

### ISSUE THREAD

**Issue by sandeepsinghmbbs** [flutterjanus/flutter_janus_client#130]
how to add Simulcast support in video room plugin?

**Comment by shivanshtalwar0** [comment]
I haven't tested it so far but hopefully in next release you could expect support in the Google meet example

**Comment by dejanp777** [comment]
@shivanshtalwar0 thanks for your work and support. Please inform us when you manage to add Simulcast

**Comment by shivanshtalwar0** [comment]
@dejanp777 , @sandeepsinghmbbs  kindly test above pr and let me know if this would work for you guys.

**Comment by sandeep23097** [comment]
Thank you.. it working fine...one more suggestion.. kindly add a simulcast flag true in publisher stream if simulcast enable for that publisher..

**Comment by shivanshtalwar0** [comment]
I will add it later, if you feel it's something you can do feel free to open a pr
