### ISSUE TITLE
hard decoding

### ISSUE THREAD

**Issue by manwithmission** [flutterjanus/flutter_janus_client#133]
Can it support hard decoding

**Comment by shivanshtalwar0** [comment]
I don't know what hard decoding is but if you talking about hardware decoding then webrtc stack relies on cpu+gpu that SOC on mobile devices therefore in my opinion it is already supporting hardware decoding

**Comment by manwithmission** [comment]
Can it switch to H264 encoding and decoding

**Comment by shivanshtalwar0** [comment]
Its something you have to set on janus level or with the help of api using configure method in case of videoroom
