### ISSUE TITLE
In Android call directly run on a Speaker mode. 

### ISSUE THREAD

**Issue by ChiragSavsani** [flutterjanus/flutter_janus_client#136]
The call feature was implemented successfully in my application. In iOS it is working as expected but not in Android.

Call directly runs on a speaker, even if Bluetooth is connected, but this is working fine in iOS. Are there any methods or other things we need to take care of in Android?

**Comment by shivanshtalwar** [comment]
For native you need to use flutter webrtc i/o methods 
Look here for reference https://github.com/flutter-webrtc/flutter-webrtc/blob/1b628ceb014232a4e99c9895ff257ffd17bc4ff7/lib/src/helper.dart#L80
Therefore you need to use
```dart
Helper.selectAudioOutpu(deviceIdOfBluetoothDevice)
```
