### ISSUE TITLE
Audio Output on IOS

### ISSUE THREAD

**Issue by Adrien300101** [flutterjanus/flutter_janus_client#150]
I am using the janus_client to create a videoroom in janus server. The audio works fine on android, it is output from the speakers however on IOS the output is not from the speakers and so the sound is low.

**Comment by shivanshtalwar** [comment]
this library relies on flutter_webrtc so you should use Helper class to enableSpeakerPhone to get output from speaker rather than ear-piece

**Comment by shivanshtalwar** [comment]
Closing
