### ISSUE TITLE
isUnifiedPlan = true is not working

### ISSUE THREAD

**Issue by anewgate** [flutterjanus/flutter_janus_client#153]
Hi ~ everyone.

I am using the video call plugin.
If you set isUnifiedPlan = true
Remote video cannot be received.
I would be grateful if you could tell me how.

Thank you.

**Comment by shivanshtalwar** [comment]
If you set isUnified plan to false remotetrack will not work instead you will receive remotestream

**Comment by anewgate** [comment]
Thank you for the reply.
But both remoteTrack and remoteStream do not work.

**Comment by shivanshtalwar** [comment]
Can you share the code snippet that is not working or example project with minimal reproduction that i can run and investigate

**Comment by anewgate** [comment]
> Can you share the code snippet that is not working or example project with minimal reproduction that i can run and investigate




I just downloaded the master branch code and ran it.
Mainly used for Android, iPhone, and iPad.
I also used the MacBook Pro's Chrome web browser, but the results were the same.

Also, I tried running the https://flutterjanus.github.io/flutter_janus_client/ link and the result was the same.

The code was executed as is without any changes, and when debugging, the remoteTrack event was not called.
     publishVideo.remoteTrack?.listen((event) async {
       if (event.track != null && event.flowing == true) {
         remoteVideoStream?.addTrack(event.track!);
         _remoteVideoRenderer.srcObject = remoteVideoStream;
         // this is done only for web since web api are muted by default for local tagged mediaStream
         if (kIsWeb) {
           _remoteVideoRenderer.muted = false;
         }
       }
     });

However, by changing the isUnifiedPlan value in the code below from true to false, I was able to receive remote video.
client = JanusClient(transport: ws, iceServers: [RTCIceServer(urls: "stun:stun.voip.eutelia.it:3478", username: "", credential: "")], isUnifiedPlan: true);
  
By looking at the sdp value of the offer or answer sent every time the isUnifiedPlan value is changed, we checked whether UnifiedPlan was set properly and confirmed that the isUnifiedPlan setting was working properly.

![IMG_0186](https://github.com/flutterjanus/flutter_janus_client/assets/2355470/6d70f9c7-fb04-453e-9c4e-ddccda8ae3cb)

<img width="1063" alt="스크린샷 2024-01-13 오후 10 42 37" src="https://github.com/flutterjanus/flutter_janus_client/assets/2355470/0c625a58-6f6b-4180-b861-75812086982f">

**Comment by shivanshtalwar** [comment]
lmk if it works @anewgate

**Comment by anewgate** [comment]
@shivanshtalwar 
I also confirmed that the unified plan works well in the master branch.
thank you so so so so so much. :)
