### ISSUE TITLE
join google meet only as audience not publishing anything

### ISSUE THREAD

**Issue by braysonjohn148** [flutterjanus/flutter_janus_client#158]
I am able to get Google Meet working fine. But I am building a different App like InstaLive, users can enter a room see comments, and view videos and audio but it is not publishing anything.

**Comment by shivanshtalwar** [comment]
It is straightforward
The live broadcaster publish his media to videoroom
Then you do rtp forward of that publisher to a streaming plugin and for messages you attach a text room plugin, please refrain from opening an issue instead ask these questions in discussions

**Comment by braysonjohn148** [comment]
I tried joining as a subscriber

await videoPlugin!.joinSubscriber(roomId);

I get error : Unhandled Exception: JanusError{ error_code: 429, error: Missing mandatory element (feed), pluginName: videoroom, event: null,}

**Comment by shivanshtalwar** [comment]
No you can't have subscriber feeds or information of feeds without joining as publisher if you are talking about video room what i suggested you is entirely different and scalable architecture you can't solely rely on video room to solve your problems

**Comment by shivanshtalwar** [comment]
Yes i get that but you can create publisher without publishing anything just for observing events and other videoroom specific stuff which then you can use to attach subscriber handles

**Comment by braysonjohn148** [comment]
setting 
mediaConstraints: { 
      'video': false,
      'audio': false
    }
i do not receive any video from subscriber. I think there is an error

**Comment by shivanshtalwar** [comment]
No you don't have to use initMediaStream it is used when you want to publish a media, in your case you should just attach the plugin joinPublisher and listen to events to subscribe to other publisher in the room

**Comment by braysonjohn148** [comment]
`  joinRoom(StreamRoom room) async {
    if (session == null) {
      await initialize();
    }

    dbJoinRoom(room.roomId);//notifying my own server
 
    videoPlugin = await attachPlugin();
    await eventMessagesHandler(room.roomId);
  
    await videoPlugin?.joinPublisher(room.roomId,
        displayName: userController.user!.username, pin: '');
  }`
This works perfectly i can join a room without publishing anything. 

So after joining the stream and viewing video, incase i want to publish my video i am calling this:

` showMyVideo() async {
    localVideoRenderer = StreamRenderer('local').obs;

    await localVideoRenderer.value.init();

    localVideoRenderer.value.mediaStream =
        await videoPlugin?.initializeMediaDevices(simulcastSendEncodings: [
    .....//removed to reduce space
    ], mediaConstraints: { 
      'video': {'width': 1280, 'height': 720},
      'audio': true
    });
    localVideoRenderer.value.videoRenderer.srcObject =
        localVideoRenderer.value.mediaStream;
    localVideoRenderer.value.publisherName = "You";
    localVideoRenderer.value.publisherId = userController.user!.uuid.toString();

    videoState.value.streamsToBeRendered
        .putIfAbsent('local', () => localVideoRenderer.value);

await videoPlugin?.configure();
`

**Comment by shivanshtalwar** [comment]
You can take paid consultation or sponsor this project and i will write basic example for functionality that you need, anyway it's hard for me to help you by looking at code snippet maybe you can share a basic example as a repo and maybe when i get time i will look at it and suggest changes
