### ISSUE TITLE
Cant use RTCIceServer without credential/password

### ISSUE THREAD

**Issue by Clon1998** [flutterjanus/flutter_janus_client#164]
Hey,
the current implementation of your `RTCIceServer` class contains a bug that causes an issue on the native side while building the peerconnection.

In particular, it is impossible to add/use Ice candidates that do not enforce a username/credential as the `toMap()` method will include these fields with values `null` when submitting the init request to the platform code.

**Comment by shivanshtalwar** [comment]
You are right it can be easily solved, by adding a null check in `toMap` would you like to do a pr for the same?

**Comment by Clon1998** [comment]
> You are right it can be easily solved, by adding a null check in `toMap` would you like to do a pr for the same?

Just created the PR
