### ISSUE TITLE
Streaming plugin: Cannot watchStream other mount point after stopStream 

### ISSUE THREAD

**Issue by getsolutionstz** [flutterjanus/flutter_janus_client#169]
I want to use the same plugin handle to watch different streams. But when I **stopStream()**, then **watchStream(mtpointId)**, and **startStream()**, the stream does not play.

I observed that when I **stopStream()**
`{event: {janus: event, session_id: 6076152537598841, transaction: e0142190-a972-42c5-ba5b-c9a1137b702f, sender: 5451666764555511, plugindata: {plugin: janus.plugin.streaming, data: {streaming: event, result: {status: stopping}}}}, jsep: null}`

`{event: {janus: hangup, session_id: 6076152537598841, sender: 5451666764555511, reason: Close PC}, jsep: null}`

Is it okay to get **hangup** after stopping? But after getting **hangup**. I cannot use the handle to watch any other stream.

I tried **PauseStream()**, but I do not get **hangup**. And when I reopen the stream I can play the stream just fine.

**Comment by shivanshtalwar** [comment]
It is normal behaviour of janus server you should refer to janus server documentation
