### ISSUE TITLE
how to build android app

### ISSUE THREAD

**Issue by interfaith** [flutterjanus/flutter_janus_client#172]
The new java/gradle versions are a headache.

**Comment by shivanshtalwar** [comment]
I haven't built native app in a while but i am sure if you follow flutter_webrtc build instructions it wouldn't be hard

**Comment by interfaith** [comment]
Yes, following all the chat gtp tips on a Java 17 update. If I get it, I
will post it.

**Comment by interfaith** [comment]
The latest Android Studio (ladybug) is known to have a "bug" for flutter
builds :) uggg
So a working upgrade maybe forthcoming after a ladybug downgrade.. haha

**Comment by shivanshtalwar** [comment]
Thanks for the update will pin this issue for future reference of other users closing now.
