### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by gc-robotics** [flutterjanus/flutter_janus_client#31]
I/org.webrtc.Logging(14526): EglRenderer: Duration: 4014 ms. Frames received: 0. Dropped: 0. Rendered: 0. Render fps: .0. Average render time: NA. Average swapBuffer time: NA.
I/org.webrtc.Logging(14526): EglRenderer: Duration: 4008 ms. Frames received: 0. Dropped: 0. Rendered: 0. Render fps: .0. Average render time: NA. Average swapBuffer time: NA.
I/FlutterWebRTCPlugin(14526): getUserMedia(audio): mandatory: [], optional: [googNoiseSuppression: true, googEchoCancellation: true, echoCancellation: true, googEchoCancellation2: true, googDAEchoCancellation: true]
E/rtc     (14526): #
E/rtc     (14526): # Fatal error in: ../../../../usr/local/google/home/sakal/code/webrtc-aar-release/src/pc/peer_connection.cc, line 1989
E/rtc     (14526): # last system error: 0
E/rtc     (14526): # Check failed: IsUnifiedPlan()
E/rtc     (14526): # GetTransceivers is only supported with Unified Plan SdpSemantics.
F/libc    (14526): Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 14599 (signaling_threa), pid 14526 (_client_example)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***

**Comment by shivanshtalwar0** [comment]
Upgrade flutter_webrtc version to latest in pubspec.yaml file closing
