### ISSUE TITLE
In videoroom v2 example, with 3 users, only 2 videos displayed per device.

### ISSUE THREAD

**Issue by alsiPanda** [flutterjanus/flutter_janus_client#32]
@shivanshtalwar0 I was trying out the videoroom v2 example, and kept facing the following problem:

1) when using 3 virtual phones on my pc, each device only shows 2 videos, one from localrenderer, and another from one of the two other devices. Sometimes one of the device is only showing the local video.
2) when using 2 virtual device, and 1 physical device, one of the virtual device shows all 3 streams, but the other virtual device and physical device only show localrenderer.

The only change to the example code I have made is the Janus url, which points to my gcp server, which hosts janus, and the username while registering so all three devices have different usernames. 

My understanding of Janus and webrtc isn't really that deep, so do I need change or add something else in the example code ?

**Comment by shivanshtalwar0** [comment]
In my experience this seems like ice connection failed issue it can happen due to variety of reasons
Make sure stun server used in janus configuration is working you can make sure it is working by trying trickle test 
Ice server url on client side that is janus client side should be same not necessarily but in my experience it works fine if it is same as stun server used in janus configuration
Let me know if that helps

**Comment by alsiPanda** [comment]
@shivanshtalwar0  I tried using Google stun servers, one as well as multiple, but that resulted in only localrenderer showing up. 
I am currently checking the Janus configuration, but it should be one of Google's stun servers.

**Comment by shivanshtalwar0** [comment]
Are you using docker for janus?

**Comment by alsiPanda** [comment]
Yes, the atyenoria repo

**Comment by shivanshtalwar0** [comment]
Why don't you try my docker setup
And see if that works for you coz i deployed it and tested it with v2 api
it was working fine except multistream support
Look for janusdocker in my profile

**Comment by alsiPanda** [comment]
@shivanshtalwar0 installed the janus from your profile. Do I need to anything else ? like configuring my nginx for janus. My previous janus setup was accessed on `http://<server_ip>:8088/janus` for rest, but currently I am unable to connect to that port.

**Comment by shivanshtalwar0** [comment]
Only if you want to change current janus configuration just use docker
compose up -d
To run it in detached mode
It should work once service is up just reverse proxy to http port said ws
port in your server nginx conf

**Comment by alsiPanda** [comment]
`docker-compose up -d` didnt work out, at first it gave some version error , so i removed the version from docker-compose.yaml, then it showed error related to `janus-multistreaming`. I was able to install using `docker build` and `docker run`. But cant seem to figure to how to reverse proxy to the new janus, as in which port to proxy_pass, etc. If possible, can you share the code for reverse proxy from your nginx.conf ?

**Comment by shivanshtalwar0** [comment]
Actually if you are running docker container without using docker compose
you should use
docker run -itd -p 8088:8088 -p 8188:8188 --name myjanus <docker image
built and tagged by you>

Once built docker build

Docker compose should also work fine make should you are running latest
docker compose version

Regarding port mapping in that case

You can get all port mapping from command
docker ps -a

**Comment by alsiPanda** [comment]
I ran this : `docker run -itd -p 8088:8088 -p 8188:8188 --name myjanus <docker image built and tagged by you>` , setup done. In the app, ` rest = RestJanusTransport(url: 'http://<server_ip>:8088/rest'); ` - when I use this, or use https instead, I get the following error: `Unhandled Exception: Connection to given url can't be established
 reason:-Janus Server not live or incorrect url/path specified`

**Comment by shivanshtalwar0** [comment]
Http should work but i would advise you to install nginx and setup reverse
proxy to docker ip and respective port for websocket or rest you can look
at my nginx conf here

If you using multistream

https://github.com/shivanshtalwar0/JanusDocker/blob/main/JanusMultiStreaming/nginx/sites-available/unified-janus.onemandev.tech

Here in the conf i have reverse proxied to docker ip and port using nginx
and enabled ssl encryption using certbot

**Comment by alsiPanda** [comment]
I have added the following to my nginx file - 

`map $http_upgrade $connection_upgrade {
        default upgrade;
        '' close;
}

upstream websocket {
        server 127.0.0.1:8081;
}
upstream rest {
        server 127.0.0.1:8088;
}

server {
        listen 80;
        listen [::]:80;
#       server_name _;
        location /websocket {
            proxy_pass http://websocket;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;
            proxy_set_header Host $host;
        }
        location /rest/ {
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_pass http://rest/janus/;
        }
}`

After that when I use the following url for RestJanusTransport - `http://<server_ip>/rest`, I am still getting the Incorrect url/path error

**Comment by shivanshtalwar0** [comment]
Let's connect on skype call

**Comment by alsiPanda** [comment]
@shivanshtalwar0 , sorry but coming to Skype won't be possible for me, if need be I can send the code for my entire Nginx conf, as well as the slightly edited code for videoroom v2 example, would that be helpful ?

**Comment by shivanshtalwar0** [comment]
First of all make sure you are able to access janus server locally
By running
curl 127.0.0.1:8088/janus/info

If it returns response that means ut is working and then setup reverse
proxy accordingly

**Comment by alsiPanda** [comment]
`curl 127.0.0.1:8088/janus/info` - this worked on the server side.
`http://<server_ip>:8088/janus/info` this worked in browser. So I am assuming reverse-proxy worked ?
In app, I used `http://<server_ip>:8088/janus` in the RestJanusTransport, after which I am able to see localrenderer but not the remoterenderers.

**Comment by shivanshtalwar0** [comment]
So considering nginx conf that you mentioned earlier janus server url
should be
http://myserver.com/websocket
As for rest it should be
http://myserver.com/rest

And you can test whether reverse proxy worked by trying
http://myserver.com/rest/info

**Comment by shivanshtalwar0** [comment]
Make sure you are using https for doing it it can be the other reason for
your problem

**Comment by alsiPanda** [comment]
http://<server_ip>/rest/info is working in the browser. But http://<server_ip>/rest gives incorrect url error. I tried adding port numbers - 80, 8088 to above ip, but it didn't work. I also tried ws://<server_ip>/websocket in WebsocketJanusTransport but I got - connection was not upgraded to websocket.

PS: going to try out https next.

**Comment by alsiPanda** [comment]
@shivanshtalwar0 , any other possible reason that remoterenderer not showing ? https will require getting a domain name and all. Summarizing, So far setup is working and reverse proxy is also working, as tested using /info in the browser and server. Using http://<server_ip>:8088/janus directly in the RestJanusTransport works. But remoterenderers not showing up. 

Could it have anything to do with ip address of all the device being same or the server bandwidth being low.

**Comment by shivanshtalwar0** [comment]
Well honestly I haven't tested it on http and i am preety sure it has got something to do with janus server or http connection
I will try it on http when i get time until then if possible you could try on https by getting tech domain and other cool stuff by applying for GitHub education if you got id card of an institute ;)

**Comment by shivanshtalwar0** [comment]
Replace it with official Janus demo url from config map
My servers are down for a while will make them up later

**Comment by alsiPanda** [comment]
So I tried with the examples folder directly and only replaced displayed name and the urls. In JanusClient I used rest instead of ws. In Videoroom I can see only localrenderer.

**Comment by shivanshtalwar0** [comment]
Are you sure you not using unified plan?

**Comment by alsiPanda** [comment]
I downloaded the janus_client V2 version instead of master from GitHub. The page I ran is videoroom and videoroomV2.

**Comment by shivanshtalwar0** [comment]
And are you using janus official demo url?

**Comment by alsiPanda** [comment]
In VideoRoom_V2.dart (Not useing ws because getting an error related websocket)
`rest =
          RestJanusTransport(url: 'https://mywebsite.xyz/rest/');
      ws = WebSocketJanusTransport(
          url: 'wss://mywebsite.xyz/websocket');
      j = JanusClient(transport: rest, iceServers: [
        RTCIceServer(
            url: "stun:stun.voip.eutelia.it:3478", username: "", credential: "")
      ]);`

In conf.dart
`var servers = [
  'wss://kosmosnetworkapps.xyz/websocket',
  'wss://janus.conf.meetecho.com/ws',
  'https://kosmosnetworkapps.xyz/rest/',
  'wss://janus.conf.meetecho.com/ws',
  'wss://kosmosnetworkapps.xyz/websocket',
  'https://kosmosnetworkapps.xyz/rest/'
];
Map<String, String> servermap = {
  'janus_ws':'wss://janus.conf.meetecho.com/ws',
  'onemandev_master_ws': 'wss://kosmosnetworkapps.xyz/websocket',
  'onemandev_master_rest': 'https://kosmosnetworkapps.xyz/rest/',
  'onemandev_unified_rest': 'https://kosmosnetworkapps.xyz/rest/',
  'onemandec_unified_ws': 'wss://kosmosnetworkapps.xyz/websocket'
};`

**Comment by shivanshtalwar0** [comment]
As i can see you are using your own server url first try with janus
official demo url

**Comment by alsiPanda** [comment]
Tried the meetecho url everywhere, as you suggested, the example code is working perfectly. I assume that means, the problem is with the Janus server setup. Or maybe, the Nginx configuration for the Janus docker.

**Comment by shivanshtalwar0** [comment]
Yes, it must be something to do with janus configuration or janus server
itself

**Comment by alsiPanda** [comment]
@shivanshtalwar0 , I did a thorough recheck and finally managed to get things working using Janus installed on my server.
My modified version - same as original issue, one device shows all 3 , other two devices show only 2 /3.
Example with my server url - the first device shows nothing, other two device show only 2/3, self and the first one.

**Comment by alsiPanda** [comment]
I think, I may have written it the wrong way. But basically I am back to where this issue started. The videoroom is not showing all the users videos. One of the device is showing all 3, and the other  2 are only showing 2. So I am finally getting the same results using the the same Janus docker installation as yours , as I was getting earlier with the atyenoria repo.

**Comment by shivanshtalwar0** [comment]
Well in that case i will have to check it probably issue related to
videoroom example

**Comment by alsiPanda** [comment]
@shivanshtalwar0 Thanks for looking into it. The problem only appears in 2+ devices. Will wait for your reply before trying anything else.

**Comment by alsiPanda** [comment]
@shivanshtalwar0 , Anyway I can help, maybe test in a specific way, or try some changes out, I would be happy to help.

**Comment by shivanshtalwar0** [comment]
Definitely i will let you know once i have done some changes you can test 😊

**Comment by shivanshtalwar0** [comment]
@alsiPanda  I think this issue is there because lorenzo merged multistream in master branch for janusgateway and videoroom example needs to accommodate those changes you can still make existing example work by setting up janusgateway version prior to multistream support
