### ISSUE TITLE
Could not build the application for the simulator.

### ISSUE THREAD

**Issue by osamaegy** [flutterjanus/flutter_janus_client#33]
`Error output from Xcode build:
↳
    ** BUILD FAILED **

Xcode's output:
↳
    In file included from /Users/osama/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_webrtc-0.6.3/ios/Classes/FlutterRTCVideoRenderer.m:9:
    In file included from /Users/osama/Developer/wpzag/ios/Pods/Libyuv/headers/libyuv.h:16:
    In file included from /Users/osama/Developer/wpzag/ios/Pods/Headers/Public/libyuv/convert.h:21:
    /Users/osama/Developer/wpzag/ios/Pods/Headers/Public/libyuv/planar_functions.h:563:26: warning: this function declaration is not a prototype [-Wstrict-prototypes]
    ARGBBlendRow GetARGBBlend();
                             ^
                              void
    1 warning generated.
    /Users/osama/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_webrtc-0.6.3/ios/Classes/FlutterRTCMediaStream.m:172:18: warning: unused variable 'requestAccessForVideo' [-Wunused-variable]
                BOOL requestAccessForVideo
                     ^
    /Users/osama/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_webrtc-0.6.3/ios/Classes/FlutterRTCMediaStream.m:369:29: warning: 'devicesWithMediaType:' is deprecated: first deprecated in iOS 10.0 - Use AVCaptureDeviceDiscoverySession instead. [-Wdeprecated-declarations]
            && [AVCaptureDevice devicesWithMediaType:mediaType].count == 0) {
                                ^
    In module 'WebRTC' imported from /Users/osama/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_webrtc-0.6.3/ios/Classes/FlutterRTCMediaStream.m:3:
    In module 'AVFoundation' imported from /Users/osama/Developer/wpzag/ios/Pods/GoogleWebRTC/Frameworks/frameworks/WebRTC.framework/Headers/RTCVideoFrame.h:11:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.4.sdk/System/Library/Frameworks/AVFoundation.framework/Headers/AVCaptureDevice.h:103:1: note: 'devicesWithMediaType:' has been explicitly marked deprecated here
    + (NSArray<AVCaptureDevice *> *)devicesWithMediaType:(AVMediaType)mediaType API_DEPRECATED("Use AVCaptureDeviceDiscoverySession instead.", ios(4.0, 10.0), macos(10.7, 10.15));
    ^
    /Users/osama/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_webrtc-0.6.3/ios/Classes/FlutterRTCMediaStream.m:451:24: warning: incompatible pointer types assigning to 'RTCCameraVideoCapturer *' from 'FlutterRPScreenRecorder *' [-Wincompatible-pointer-types]
        self.videoCapturer = screenCapturer;
                           ^ ~~~~~~~~~~~~~~
    /Users/osama/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_webrtc-0.6.3/ios/Classes/FlutterRTCMediaStream.m:479:44: warning: 'devicesWithMediaType:' is deprecated: first deprecated in iOS 10.0 - Use AVCaptureDeviceDiscoverySession instead. [-Wdeprecated-declarations]
      NSArray *videoDevices = [AVCaptureDevice devicesWithMediaType:AVMediaTypeVideo];
                                               ^
    In module 'WebRTC' imported from /Users/osama/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_webrtc-0.6.3/ios/Classes/FlutterRTCMediaStream.m:3:
    In module 'AVFoundation' imported from /Users/osama/Developer/wpzag/ios/Pods/GoogleWebRTC/Frameworks/frameworks/WebRTC.framework/Headers/RTCVideoFrame.h:11:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.4.sdk/System/Library/Frameworks/AVFoundation.framework/Headers/AVCaptureDevice.h:103:1: note: 'devicesWithMediaType:' has been explicitly marked deprecated here
    + (NSArray<AVCaptureDevice *> *)devicesWithMediaType:(AVMediaType)mediaType API_DEPRECATED("Use AVCaptureDeviceDiscoverySession instead.", ios(4.0, 10.0), macos(10.7, 10.15));
    ^
    /Users/osama/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_webrtc-0.6.3/ios/Classes/FlutterRTCMediaStream.m:488:44: warning: 'devicesWithMediaType:' is deprecated: first deprecated in iOS 10.0 - Use AVCaptureDeviceDiscoverySession instead. [-Wdeprecated-declarations]
      NSArray *audioDevices = [AVCaptureDevice devicesWithMediaType:AVMediaTypeAudio];
                                               ^
    In module 'WebRTC' imported from /Users/osama/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_webrtc-0.6.3/ios/Classes/FlutterRTCMediaStream.m:3:
    In module 'AVFoundation' imported from /Users/osama/Developer/wpzag/ios/Pods/GoogleWebRTC/Frameworks/frameworks/WebRTC.framework/Headers/RTCVideoFrame.h:11:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.4.sdk/System/Library/Frameworks/AVFoundation.framework/Headers/AVCaptureDevice.h:103:1: note: 'devicesWithMediaType:' has been explicitly marked deprecated here
    + (NSArray<AVCaptureDevice *> *)devicesWithMediaType:(AVMediaType)mediaType API_DEPRECATED("Use AVCaptureDeviceDiscoverySession instead.", ios(4.0, 10.0), macos(10.7, 10.15));
    ^
    5 warnings generated.
    In file included from /Users/osama/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_webrtc-0.6.3/ios/Classes/FlutterRTCFrameCapturer.m:10:
    In file included from /Users/osama/Developer/wpzag/ios/Pods/Libyuv/headers/libyuv.h:16:
    In file included from /Users/osama/Developer/wpzag/ios/Pods/Headers/Public/libyuv/convert.h:21:
    /Users/osama/Developer/wpzag/ios/Pods/Headers/Public/libyuv/planar_functions.h:563:26: warning: this function declaration is not a prototype [-Wstrict-prototypes]
    ARGBBlendRow GetARGBBlend();
                             ^
                              void
    1 warning generated.
    Command CompileSwift failed with a nonzero exit code
    /Users/osama/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/janus_client-2.0.0-beta/ios/Classes/FlutterJanusClientPlugin.m:8:9: fatal error: 'flutter_janus_client-Swift.h' file not found
    #import "flutter_janus_client-Swift.h"
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.4.99. (in target 'FMDB' from project 'Pods')
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.4.99. (in target 'AppAuth' from project 'Pods')
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.4.99. (in target 'GoogleSignIn' from project 'Pods')
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.4.99. (in target 'Libyuv' from project 'Pods')
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.4.99. (in target 'Flutter' from project 'Pods')
    warning: Capabilities for Signing & Capabilities may not function correctly because its entitlements use a placeholder team ID. To resolve this, select a development team in the Runner editor. (in target 'Runner' from project 'Runner')

Could not build the application for the simulator.
Error launching application on iPhone 12 Pro Max.`

**Comment by shivanshtalwar0** [comment]
Delete ios folder and run flutter create . Again in example directory that should work, if not then feel free to open this issue again

**Comment by osamaegy** [comment]
> Delete ios folder and run flutter create . Again in example directory that should work, if not then feel free to open this issue again

i have done that but  still getting the same error

**Comment by shivanshtalwar0** [comment]
I will try it within few days and let you know

**Comment by osamaegy** [comment]
ok thanks !
