### ISSUE TITLE
null safe library

### ISSUE THREAD

**Issue by mail2mhossain** [flutterjanus/flutter_janus_client#38]
Non-nullable instance field 'publishVideo' must be initialized.
Try adding an initializer expression, or a generative constructor that initializes it

The library 'package:janus_client/Plugin.dart' is legacy, and should not be imported into a null safe library.

**Comment by shivanshtalwar0** [comment]
released new version now  supports null-safety, check https://pub.dev/packages/janus_client/versions/2.1.0-beta
