### ISSUE TITLE
when run this on iOS, xcode"flutter_janus_client-Swift.h" file not found, how to fix it 

### ISSUE THREAD

**Issue by wupengbigMarker** [flutterjanus/flutter_janus_client#39]

**Comment by shivanshtalwar0** [comment]
Delete ios folder and run `flutter create .`  in example directory and then run it will work

**Comment by wupengbigMarker** [comment]
it didn't work, I did try that serval times

**Comment by wupengbigMarker** [comment]
And my  flutter  (Channel stable, 2.5.0, on macOS 11.4 20F71 darwin-x64, locale zh-Hans-CN)

**Comment by shivanshtalwar0** [comment]
I will try it on my mac then and will get back to you

**Comment by huoda1237** [comment]
Hello, I have the same problem. Is there a solution?

**Comment by shivanshtalwar0** [comment]
Are you sure you are using v2 branch?

**Comment by shivanshtalwar0** [comment]
Can you delete pubspec.lock file and then try to run it after running `flutter pub get`

**Comment by huoda1237** [comment]
> Are you sure you are using v2 branch?

i am using the master,i will use v2 later,thank you

**Comment by huoda1237** [comment]
<img width="636" alt="截屏2021-11-01 下午3 02 30" src="https://user-images.githubusercontent.com/16382451/139634075-9e9a9d67-2792-49f0-9c98-c17c78ad9875.png">

when i use v2,it has the same problem

**Comment by shivanshtalwar0** [comment]
Try on fresh clone that should not come on v2_dev branch

**Comment by shivanshtalwar0** [comment]
try with latest release, hopefully, that should work
