### ISSUE TITLE
no streams in the data["publishers"]

### ISSUE THREAD

**Issue by RowgerGo** [flutterjanus/flutter_janus_client#43]
[http://doc.1024web.cn/server/index.php?s=/api/attachment/visitFile/sign/06501b2e3d40380a17b6b138d754aeb9](image)

**Comment by RowgerGo** [comment]
http://doc.1024web.cn/server/index.php?s=/api/attachment/visitFile/sign/06501b2e3d40380a17b6b138d754aeb9

**Comment by RowgerGo** [comment]
EventMessage{event: {janus: media, session_id: 7279768941524783, sender: 7943554953189692, type: video, receiving: true}, jsep: null}

**Comment by shivanshtalwar0** [comment]
Can you try v2_dev branch typed example and inform me whether that fixes for you?

**Comment by shivanshtalwar0** [comment]
try examples in latest release they should work
