### ISSUE TITLE
Audio in remote feed

### ISSUE THREAD

**Issue by dejanp777** [flutterjanus/flutter_janus_client#45]
Can you please help me to mute audio in remote feed. When I use getAudioTracks()[0] and I set enabled = false, I get error:
"You're trying to mute a remote track, this is not supported"
Any idea how to do it?

**Comment by shivanshtalwar0** [comment]
Can you tell me for which plugin you are referring to?

**Comment by dejanp777** [comment]
VideoRoom plugin

**Comment by shivanshtalwar0** [comment]
are you trying to achieve this in unified plan? i mean videoroom_v2_unified?

**Comment by dejanp777** [comment]
I am trying first with VideoRoom_V2.dart and then will with VideoRoom_V2_unified.dart.

**Comment by dejanp777** [comment]
Any idea how can I do this? Please

**Comment by shivanshtalwar0** [comment]
actually, this should be possible with webrtc stack itself i need to try out the dart-webrtc package  by flutter webrtc to give you any final solution

**Comment by shivanshtalwar0** [comment]
you can mute the coresponding renderer of the associated track to mute the audio, closing
