### ISSUE TITLE
Web platform streams issues on Chrome/Safari browsers

### ISSUE THREAD

**Issue by kurtiev** [flutterjanus/flutter_janus_client#48]
**1. CHROME**

Demo the link https://flutterjanus.github.io/flutter_janus_client/example/build/web/#/streaming_v2 fails with next error:

```
  Uncaught Error: Failed to construct 'RTCPeerConnection': Plan B SDP semantics is a legacy version of the Session Description Protocol that has severe compatibility issues on modern browsers and is no longer supported. See https://www.chromestatus.com/feature/5823036655665152 for more details, including the possibility of registering for a Deprecation Trial in order to extend the Plan B deprecation deadline for a limited amount of time.
    at new WrappedRTCPeerConnection (<anonymous>:275:28)
    at Object.avJ (main.dart.js:18986)
    at main.dart.js:64533
    at adx.a (main.dart.js:13242)
    at adx.$2 (main.dart.js:32413)
    at Object.B (main.dart.js:13228)
    at a_2.a7_ (main.dart.js:64539)
    at a_2.AY (main.dart.js:64522)
    at main.dart.js:65231
    at adx.a (main.dart.js:13242)
```

Unified stream works fine
https://flutterjanus.github.io/flutter_janus_client/example/build/web/#/streaming_v2_unified

Chome info:
_Version 96.0.4664.110 (Official Build) (x86_64)_

So, should we all now switch Janus settings to Unified plan? According to [this link](https://chromestatus.com/feature/5823036655665152) Plan-B wouldn't be supported by Chrome. 

**2. On Firefox both kinds of streams work fine.**

**3. On Safari Streams doesn't work at all.**

**Comment by kurtiev** [comment]
From [docs](https://janus.conf.meetecho.com/docs/JS.html)

_Notice that the janus.js library makes use of the features made available by the webrtc-adapter shim, which means that your web application should always include it as a dependency._

Is that package supposed use this adapter already?

**Comment by shivanshtalwar0** [comment]
The thing is janusjs needs to work  for most browser on the other hand for webrtc stack this library entirely depends on flutter_webrtc which itself has some limitation when it comes to unified plan in web, although its in my todo list to finalize it  by trying new dart-webrtc by cloudwebrtc atleast for web and for other platform we can stick with flutter_webrtc
If you have time to contribute you can open pull request we can discuss game plan on Google meet or skype

**Comment by shivanshtalwar0** [comment]
this is resolved you can try latest example
