### ISSUE TITLE
how can i use mute unmute audio room

### ISSUE THREAD

**Issue by RRohitM** [flutterjanus/flutter_janus_client#49]
How to implement mute unmute feature in audio room there is no method implemented for mute unmute and indicate other users who is muted.

**Comment by shivanshtalwar0** [comment]
That is simple and straightforward, all you need to do is use configure method with muted property as true or false ,
If you adminstrator or audioroom you can individual participants via mute/unmute request along with secret of room
For clear picture refer https://janus.conf.meetecho.com/docs/audiobridge.html
You can find configure method in v2_dev branch which is stable yet features latest and greatest features,
I recommend you check that out here
https://github.com/flutterjanus/flutter_janus_client/tree/v2_dev

**Comment by shivanshtalwar0** [comment]
https://github.com/flutterjanus/flutter_janus_client/blob/de9470b946caaf7328a74086458ae34bb965d159/lib/WrapperPlugins/JanusAudioBridgePlugin.dart#L107
