### ISSUE TITLE
issue with print EglRenderer logs after end call how to stop?

### ISSUE THREAD

**Issue by RRohitM** [flutterjanus/flutter_janus_client#50]
I Have to use Janus client for audio and video calls when I disconnect the call I have cleared all the objects and disposed of video rendering but logs are always shown in consol how to fix that

EglRenderer: Duration: 4003 ms. Frames received: 0. Dropped: 0. Rendered: 0. Render fps: .0. Average render time: NA. Average swapBuffer time: NA.

**Comment by shivanshtalwar0** [comment]
These logs are generated from flutter_webrtc, you can ask this question there
