### ISSUE TITLE
VideoRoom: RoomId wrong type

### ISSUE THREAD

**Issue by UserSense** [flutterjanus/flutter_janus_client#51]
Janus VideoRoom does not require that the roomId is of type int. It is allowed to use strings instead if the option: string_ids is set to true.

Holds also for all participants uuid.

**Comment by shivanshtalwar0** [comment]
Yes that might have missed out but maybe in next release we can accommodate for string as room id. Although if you want you can open a pr and i would gladly accept it since i am bit busy these days

**Comment by UserSense** [comment]
I'll see what I can do. I rather help improving this plugin, than creating one on my own.

**Comment by UserSense** [comment]
Should not have been closed. roomId should be of type dynamic. 

string_ids == false: Janus expects int, and returns int for publisherId
string_ids == true: Janus expects string, and returns string for publisherId

I will run my code again, and provide a list of places where updates are required.

**Comment by shivanshtalwar0** [comment]
ahh i see fixing it right away

**Comment by shivanshtalwar0** [comment]
@UserSense you can verify now should work fine across all major plugins

**Comment by UserSense** [comment]
I will do a check for videoRoom with string_ids == true.

**Comment by UserSense** [comment]
At the moment I found the following in VideoRoom:

interfacese/video_room/video_room/events/video_room_event.dart

copyWith

`int? room,` -> `dynamic room`,

VideoRoomEvent.fromMap

`map['room'] as int,` -> `map['room']`,


interfacese/video_room/video_room/events/video_room_joined_event.dart

`int? id;` -> `dynamic id;` in `VideoRoomJoinedEvent`
`int? id;` -> `dynamic id;` in `Publishers`

Example response when joining, both room and id are strings in this case.

`{videoroom: joined, room: 198, description: Room 198, id: e7f8e202-61ca-4b7e-bec0-828610f1e917, private_id: 348602811, publishers: [], attendees: []}`

interfacese/video_room/video_room/events/video_room_list_participants.dart

`int? id;` -> `dynamic id;` in `Participants`

**Comment by MrNB0dy** [comment]
hi, the issue does not seem to have been fixed

**Comment by shivanshtalwar0** [comment]
now check made some fixes

**Comment by shivanshtalwar0** [comment]
Closing then, let me know if you see any discrepancies related to this change or the issue in general
