### ISSUE TITLE
Not adhering to naming conventions

### ISSUE THREAD

**Issue by UserSense** [flutterjanus/flutter_janus_client#52]
Directories en filenames should be having the following format: lowercase_with_underscores

https://dart.dev/guides/language/effective-dart/style

**Comment by shivanshtalwar0** [comment]
Maybe you can open a pr i would  accept

**Comment by UserSense** [comment]
I'll see what I can do. I rather help improving this plugin, than creating one on my own.

**Comment by shivanshtalwar0** [comment]
@UserSense appreciate it! open a pr code gets merged and you will be added as a contributor + member of core team :)

**Comment by UserSense** [comment]
Could it be that i'm not allow to push a new branch for this issue.

I only renamed the directories and files, and changed all references to it.

There are still other naming issues regarding variables (arround 30 remaining). This will be something for a new issue.

**Comment by shivanshtalwar0** [comment]
you can fork it and submit a pull request you can't create a new branch until you join as an member of this project flutterjanus

**Comment by shivanshtalwar0** [comment]
pr merged thank you  very much for valuable and quick contribution will add you to contributors list 🥇
