### ISSUE TITLE
pin field missing in joinPublisher, videoroom plugin

### ISSUE THREAD

**Issue by UserSense** [flutterjanus/flutter_janus_client#58]
A field called pin is missing as optional field in joinPublisher. Is required if a room has been created with a pin. 

I will try to provide a PR later this week.

**Comment by shivanshtalwar0** [comment]
thanks for raising it i am accommodating these changes including naming convention maybe you can help me with documentation.

**Comment by UserSense** [comment]
I will see what I can do.
