### ISSUE TITLE
getDisplayMedia, getDisplayMedia error (android 12)

### ISSUE THREAD

**Issue by UserSense** [flutterjanus/flutter_janus_client#60]
![afbeelding](https://user-images.githubusercontent.com/65860664/154694587-2ee4a892-ea5b-41ba-8063-53ba3a3e6a06.png)

1. One calls `initializeMediaDevices `with `useDisplayMediaDevice` set to `true`
2. This will trigger an adhoc permission request, which can be denied by the user.
3. If the user denies the permission request, `getDisplayMedia` will fail

This is not catched within the function, resulting in a crash.

I guess the same holds if permissions for getUserMedia are not granted, most apps check these at startup. With mediaprojection/screenshare this is not possible on newer android versions.

Two solutions:

1. Adjusting the function
2. Placing the `initializeMediaDevices` call in a try catch (Examples should use try catch as well).

The second solution could be the better one, as it enables the developer to catch the exception, but it needs to be documented.

**Comment by shivanshtalwar0** [comment]
You are right examples are not polished enough to be used in production straight away but then again pr are always welcome for such things.
