### ISSUE TITLE
apiSecret not working

### ISSUE THREAD

**Issue by baihua666** [flutterjanus/flutter_janus_client#61]
version:  janus_client:  2.2.1
line 155 of file janus_client.dart ,
constructor of JanusClient
change     
_apiSecret = _apiSecret;
to 
_apiSecret = apiSecret;

**Comment by baihua666** [comment]
OK，I also found some other questions that can be submitted together，video call plugin does not handle error events such as the registered username already exists

**Comment by shivanshtalwar0** [comment]
Awesome 👍! Thanks will add you into contributors after the pr review

**Comment by baihua666** [comment]
https://github.com/flutterjanus/flutter_janus_client/pull/62/commits
two commit tested.

**Comment by shivanshtalwar0** [comment]
Could you please add same error handling for other plugins as well?

**Comment by baihua666** [comment]
ok i'll try it, but i don't know how other plugins work and probably won't be able to test it
