### ISSUE TITLE
need minCompileSdk (31)  and JDK version is 11？  but in china  we use jdk8 lot of us，what  can  i  do for jdk8 version？

### ISSUE THREAD

**Issue by shuaixiaozhou** [flutterjanus/flutter_janus_client#64]
minCompileSdk (31) specified in a         dependency's AAR metadata (META-INF/com/android/build/

**Comment by shivanshtalwar0** [comment]
Sorry but minsdk constraints depends of flutter webrtc so maybe you can ask this question there
