### ISSUE TITLE
sip call example

### ISSUE THREAD

**Issue by skalogirou** [flutterjanus/flutter_janus_client#66]
I'm trying to create a sip client app and I cannot find an example on the latest version. Is there a particular reason that is missing?

**Comment by shivanshtalwar0** [comment]
I don't have access to sip server so that's why i was reluctant to write wrapper for sip plugin but if you follow documentation of janus and api you will be able to write it on top of it maybe you could help me write the wrapper plugin for it

**Comment by skalogirou** [comment]
I have access on sip server and I can provide you with sip credential in order for you to test it if you want.

**Comment by shivanshtalwar0** [comment]
Sure that would be very helpful, you can email them to me at shivanshtalwar0@gmail.com, in day or two i will pick up the development and release prototype example and in next version you can see sip plugin with all helper methods

**Comment by skalogirou** [comment]
Have you considered using https://github.com/flutter-webrtc/callkeep for manipulating audio streams?

**Comment by shivanshtalwar0** [comment]
it is done now only thing pending is add support for incoming call in sip example
