### ISSUE TITLE
how to receive calls when app is close or background?

### ISSUE THREAD

**Issue by RRohitM** [flutterjanus/flutter_janus_client#67]
hello @shivanshtalwar0 
I have implemented the Janus plugin for the audio and video call feature. All the feature is working fine but I want to add one more feature when the application is closed or the background incoming call is not working what I do. have you implemented anything else for this.

**Comment by shivanshtalwar0** [comment]
Well this is something you have to implement with the help of callkeep this project is merely a package that offers connectivity to janus server and apis to help you implement its plugin functionalities
