### ISSUE TITLE
IsTextureConsistent: IMGEGLImage is not consistent

### ISSUE THREAD

**Issue by fedorkarpenko1984** [flutterjanus/flutter_janus_client#74]
![issue](https://user-images.githubusercontent.com/73883259/177265332-98d8487d-1288-4071-a44b-97fc9898e93c.jpg)

I'm trying to start a call, but it doesn't go any further. Here are the logs

**Comment by shivanshtalwar0** [comment]
This seems like it is related to flutter_webrtc which this package uses as the dependency for managing webrtc stack details, maybe you can try to update the dependency of flutter_webrtc in pubspec.yaml file and let me know if it works for you
