### ISSUE TITLE
Video looks blurry 

### ISSUE THREAD

**Issue by HamidRezaBashiri** [flutterjanus/flutter_janus_client#76]
in android example video in video room is blurry and foggy i tested on emulator and physical device but on the web there is no problem 
is this problem relates to example or client it self? 
how can i fix it?
and the video call problem still exist(after accepting call screen turns black) in android example if you guide me i would be glad to help any where in project
thanks 🙏

**Comment by Jaehyeon0415** [comment]
I think problem is filterQuality.

```dart
RTCVideoView(
  remoteStream.videoRenderer,
  // change low or none
  // filterQuality: FilterQuality.high,
  objectFit: RTCVideoViewObjectFit.RTCVideoViewObjectFitCover,
)
```

**Comment by shivanshtalwar0** [comment]
Also for what its worth setting up high bitrate increase overall quality of media at the expense of more cpu usage on both janus server and client device,
Therefore closing it for now in case you have other questions feel free to ask on discussions or gitter
