### ISSUE TITLE
plugin.switchCamera();

### ISSUE THREAD

**Issue by dejanp777** [flutterjanus/flutter_janus_client#78]
Hello,
I am trying to use plugin.switchCamera(); for web implementation. 
I have provided required deviceId, but still can't get it to work. As I see, your code uses removeTrack/addTrack... is there something that I need to do after plugin.switchCamera() is called? Because other users can't see new camera.

**Comment by shivanshtalwar0** [comment]
Try https://github.com/flutterjanus/flutter_janus_client/tree/v2_dev
And let me know if it fixes the problem for you

**Comment by dejanp777** [comment]
Works fine, thank you for help! :)

**Comment by shivanshtalwar0** [comment]
Fixed in 2.2.4
