### ISSUE TITLE
How to create new video room

### ISSUE THREAD

**Issue by muhammadCodeSh** [flutterjanus/flutter_janus_client#81]
Hello it is not a issu .
I trying to create a video room with specific room id 
This is my code
`plugin.createVideoRoom()`
But i got 
This error
`[FINE] JanusClient: Track(id: 3cf07719-1855-488d-aefa-09824a866439, kind: video, label: USB2.0 VGA UVC WebCam (13d3:5a01), enabled: true, muted: false)
{error_code: 429, error: Missing mandatory element (admin_key), pluginName: videoroom}
{error_code: 426, error: No such room (1235), pluginName: videoroom}`
Please help me

**Comment by shivanshtalwar0** [comment]
You can't create/modify already existing videoroom or any janus plugin without specifying admin_key which makes sense otherwise everyone or anyone would be able to change things on your janus instance in this case i am assuming you tried it on meetecho server so they only know that admin key

**Comment by muhammadCodeSh** [comment]
there is not any document to show me how can I create my specific video room.
please explain to me how can I create a video room or show me a document

**Comment by shivanshtalwar0** [comment]
Check this out https://janus.conf.meetecho.com/docs/videoroom.html
