### ISSUE TITLE
How to implement a deafen feature

### ISSUE THREAD

**Issue by rajivaPavan** [flutterjanus/flutter_janus_client#83]
How can implement a deafen feature like in discord?

i.e. Discord gives you the option to either mute or deafen yourself. Muting yourself will prevent others in the voice channel from hearing what you are saying. Deafening yourself will prevent you from hearing others and will also mute you.

**Comment by shivanshtalwar0** [comment]
both of these things can be done simply by using transreciever apis, without any involvement of janus into picture
