### ISSUE TITLE
Why the JanusError: Already watching mountpoint?

### ISSUE THREAD

**Issue by bambinoua** [flutterjanus/flutter_janus_client#89]
I used your example to build my video page where I can add cameras on a page. I can add one camera which works fine but if I add new camera (still watching the first one) I get the error `460 Already watching mountpoint XXX`. Does it means that I can watch only single camera using your plugin? I know that Janus allows to watch view cameras at once.

**Comment by shivanshtalwar0** [comment]
Can you be more descriptive so that i can understand the whole thing?
