### ISSUE TITLE
Decline incoming call show error and doesnt kill sesion

### ISSUE THREAD

**Issue by Kevinpahlevi** [flutterjanus/flutter_janus_client#93]
i am facing some error when try to decline incoming call , it show error : 
`JanusError{ error_code : 444, error: Invalid element type (code should be an integer), pluginName: sip. event: null,}
` this error came from sip?.decline() ,  and still ringing in other device who try to call.

  janus_client: ^2.2.7
  flutter_webrtc: ^0.9.11

**Comment by shivanshtalwar** [comment]
Upgrade to 2.2.8 and that should fix your problem.
