### ISSUE TITLE
How to install latest version of janus server (multistream unified plan)?

### ISSUE THREAD

**Issue by blackbusters** [flutterjanus/flutter_janus_client#95]
Is there any documentation / link about how to install the latest version of janus server on ubuntu (20.04)?

I've seen available guide and docker that only use version 0.x (which I assume is the legacy version).

Thank you.

**Comment by shivanshtalwar0** [comment]
Please refrain from asking questions in GitHub issues of unrelated repository, as for your question
We use https://github.com/flutterjanus/JanusDocker for running Janus on local as well as for deployment on server
